### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by jdrevet** [jdrevet/Withings-SDK-iOS#10]
Swift dependencies need to be updated to be compliant with XCode 8

**Comment by nekot** [comment]
I'm trying to use this by following readme.md, but it seems we have to use new version of OAuthSwift on Xcode 8.
But in that case we have to modify WithingsMeasureAPIClient.m. 
Do you have plan to update it?

**Comment by jdrevet** [comment]
I'll release soon a new version (0.2.1) to fix this issue.
Don't hesitate to give me feedbacks about the library, to help me improve it.
