### ISSUE TITLE
Implement the Get Sleep Measures API

### ISSUE THREAD

**Issue by jdrevet** [jdrevet/Withings-SDK-iOS#2]

**Comment by robertturrall** [comment]
@jdrevet I have implemented this feature. Would you like me to publish my branch and issue a pull request for you to review?

**Comment by jdrevet** [comment]
Hi @robertturrall,
Yes, feel free to submit a pull request with your work.

**Comment by robertturrall** [comment]
Hi @jdrevet. I'd love to but will need permission to publish. Are you willing to add me as a collaborator for this purpose?

**Comment by robertturrall** [comment]
Thanks. PR is in!

**Comment by jdrevet** [comment]
I have merged the PR.
Thank @robertturrall for the contribution !
